import {
  Bell,
  Users,
  Calendar,
  MessageCircle,
  Briefcase,
  DollarSign,
  UserPlus,
  Shield,
  Megaphone,
  Store,
  Heart,
  Star,
} from 'lucide-react';

export const NOTIFICATION_ICONS = {
  FRIEND_REQUEST: UserPlus,
  FRIEND_ACCEPTED: UserPlus,
  DIRECT_MESSAGE: MessageCircle,
  GROUP_MESSAGE: Users,
  JOIN_REQUEST_ACCEPTED: Users,
  EVENT_JOINED: Calendar,
  TABLE_JOINED: Users,
  friend_request: UserPlus,
  table_invite: Users,
  TABLE_INVITE: Users,
  IDENTITY_VERIFICATION_REMINDER: Bell,
  EVENT_INTEREST_REMINDER: Calendar,
  PROMOTER_EVENT_ASSIGNED: Calendar,
  VENUE_STAFF_ASSIGNED: Shield,
  VENUE_FOLLOW: Heart,
  PLATFORM_ANNOUNCEMENT: Megaphone,
  VENDOR_LISTING_REMINDER: Store,
  VENDOR_REVIEW_RECEIVED: Star,
  VENDOR_INQUIRY_RECEIVED: Briefcase,
  VENDOR_INQUIRY_UPDATED: Briefcase,
  table_request: Users,
  TABLE_REQUEST: Users,
  TABLE_APPROVED: Users,
  TABLE_DECLINED: Users,
  TABLE_MESSAGE: MessageCircle,
  table_update: Users,
  table_full: Users,
  job_application: Briefcase,
  message: MessageCircle,
  event_reminder: Calendar,
  payment: DollarSign,
  compliance: Bell,
  system: Bell,
};

export const NOTIFICATION_COLORS = {
  FRIEND_REQUEST: 'sec-badge-silver',
  FRIEND_ACCEPTED: 'sec-badge-silver',
  DIRECT_MESSAGE: 'sec-badge-silver',
  GROUP_MESSAGE: 'sec-badge-success',
  JOIN_REQUEST_ACCEPTED: 'sec-badge-success',
  friend_request: 'sec-badge-silver',
  table_invite: 'sec-badge-success',
  table_request: 'sec-badge-success',
  TABLE_REQUEST: 'sec-badge-success',
  TABLE_APPROVED: 'sec-badge-success',
  TABLE_DECLINED: 'sec-badge-danger',
  TABLE_MESSAGE: 'sec-badge-silver',
  table_update: 'sec-badge-silver',
  table_full: 'sec-badge-gold',
  job_application: 'sec-badge-gold',
  message: 'sec-badge-silver',
  event_reminder: 'sec-badge-silver',
  payment: 'sec-badge-success',
  compliance: 'sec-badge-gold',
  system: 'sec-badge-muted',
  EVENT_INTEREST_REMINDER: 'sec-badge-silver',
  VENUE_STAFF_ASSIGNED: 'sec-badge-gold',
  VENUE_FOLLOW: 'sec-badge-gold',
  PLATFORM_ANNOUNCEMENT: 'sec-badge-silver',
  VENDOR_LISTING_REMINDER: 'sec-badge-gold',
  VENDOR_REVIEW_RECEIVED: 'sec-badge-gold',
  VENDOR_INQUIRY_RECEIVED: 'sec-badge-success',
  VENDOR_INQUIRY_UPDATED: 'sec-badge-silver',
};
